version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: opscore_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opscore
    ports:
      - "3306:3306"
    volumes:
      - opscore_db_data:/var/lib/mysql

volumes:
  opscore_db_data:
